### PR TITLE
Patch nvprof so it doesn't link outside the conda environment

### PR DESCRIPTION
**Pull request by danpetry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

When overlinking check is turned on, the following error message occurs:

```
ERROR (cuda-nvprof,bin/nvprof): runpaths ['$ORIGIN/../extras/CUPTI/lib64', '$ORIGIN/../targets/x86_64-linux/lib'] found in
/croot/cuda-nvprof_1715204971555/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac
ehold_placehold_placehold_placehold_place/bin/nvprof"
```

### CODE REVIEW

**Comment by danpetry** [comment]
@conda-forge-admin, please rerender

**Comment by danpetry** [comment]
@bdice @jakirkham

**Review by bdice — APPROVED** [review]
This seems fine to me. I'll add automerge so this can merge once CI passes.

**Comment by danpetry** [comment]
great, thanks.

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
